/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.8/userguide/multi_project_builds.html in the Gradle documentation.
 */

gradle.beforeProject {
    extensions.extraProperties["frameworkVersions"] = mapOf(
        "esdb.version" to "1.0.1",
        "spring.boot.version" to "3.4.5",
    )
    extensions.extraProperties["memorySettings"] = mapOf(
        "test.min-heap-size" to "2048m",
        "test.max-heap-size" to "4096m",
    )
}

rootProject.name = "opencqrs"
include(
    "esdb-client",
    "esdb-client-spring-boot-autoconfigure",
    "esdb-client-spring-boot-starter",
    "framework",
    "framework-test",
    "framework-spring-boot-autoconfigure",
    "framework-spring-boot-starter",
    "example-application",
)
