CREATE TABLE IF NOT EXISTS EVENTHANDLER_LOCK  (
	LOCK_KEY CHAR(36) NOT NULL,
	REGION VARCHAR(100) NOT NULL,
	CLIENT_ID CHAR(36),
	CREATED_DATE TIMESTAMP NOT NULL,
	constraint EVENTHANDLER_LOCK_PK primary key (LOCK_KEY, REGION)
);

CREATE TABLE IF NOT EXISTS EVENTHANDLER_PROGRESS (
    GROUP_KEY VARCHAR(100) NOT NULL,
    PARTITION_ID BIGINT NOT NULL,
    EVENT_ID VARCHAR(100) NOT NULL,
    constraint EVENTHANDLER_PROGRESS_PK primary key (GROUP_KEY, PARTITION_ID)
);