CREATE TABLE IF NOT EXISTS TEST_PROGRESS (
    GROUP_KEY VARCHAR(100) NOT NULL,
    PARTITION_ID BIGINT NOT NULL,
    EVENT_ID VARCHAR(100) NOT NULL,
    constraint TEST_PROGRESS_PK primary key (GROUP_KEY, PARTITION_ID)
);
